services:

  es01:
    image: elasticsearch:8.19.8
    pull_policy: never
    container_name: es01
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1536m -Xmx1536m"
    ulimits:
      memlock: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./plugins/analysis-ik:/usr/share/elasticsearch/plugins/analysis-ik:ro
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: kibana:8.19.8
    pull_policy: never
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      # - XPACK_SECURITY_ENABLED=false
    depends_on:
      - es01
    networks:
      - elastic

volumes:
  esdata:


networks:
  elastic:
